### ISSUE TITLE
nscli buy-name responds with success with insufficient funds

### ISSUE THREAD

**Issue by patrickwieth** [cosmos/sdk-tutorials#143] opened 2019-09-19 10:05 UTC
`nscli tx nameservice buy-name jack.id 5000nametoken --from jack`

or

`nscli tx nameservice buy-name jack.id 5wrgstrftoken --from jack`

both respond with 
```
"raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"\"}]",
  "logs": [
    {
      "msg_index": 0,
      "success": true,
      "log": ""
    }
  ]
```

the setup is a fresh install with instructions from tutorial, so 1000nametoken are present for jack. It works with <=1000. 
nsd shows 1 invalidtx. but nscli gives the response quoted above. 

Maybe this bug is not from sdk-application-tutorial but rather from cosmos-sdk 0.37?

**Comment by yukimura45z** [comment] 2019-09-25 00:36
I also got this response where
`$ nscli tx bank send xxx yyy 1000token` even if fund is insufficient.

**Comment by marbar3778** [comment] 2019-10-20 09:12
Debugged this at the diffusion hackathon, will fix it this coming week, sorry for the delay

**Comment by okwme** [comment] 2020-02-04 17:19
Thanks for opening this issue and apologies for the confusion you all have had!

I think this is actually expected behavior although the feedback is admittedly confusing. When you see the success message it is correct because your _transaction_ was successfully included in a block. However the _message_ inside of the block ultimately failed when it was processed by the state machine.

If you were to take the <txhash> that showed up as a response of your transaction, you should be able to run:
```
nscli q tx <txhash>
```
and it will tell you whether the _message_ was also successful. It should also give you an error message for why it did not should it have failed.

If I'm misunderstanding the problem I'd love to know more and will do my best to reproduce the error. Otherwise I'll close this issue and look for it to be re-opened should I have misunderstood.

**Closed by okwme** 2020-02-04 17:19 UTC
Labels: nameservice
